package:
  name: tex
  version: "1.8"

source:
  fn: tex-1.8.tar.gz
  url: https://pypi.python.org/packages/97/64/7f5d45a782be53b88e5d0963b1ef9a9fc3c6ff409fbbd2006418c5b285ff/tex-1.8.tar.gz
  md5: ac0e996e8154cd7e64ab84d2cc74d1cf
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tex = tex:main
    #
    # Would create an entry point called tex that calls tex.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.profv.de/python-tex/
  license: MIT License
  summary: 'Convert LaTeX or TeX source to PDF or DVI, and escape strings for LaTeX.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
