# More information on meta.yaml: http://docs.continuum.io/conda/build.html
package:
  name: tex
  version: "1.8"

source:
  fn: tex-1.8.tar.gz
  url: https://pypi.python.org/packages/97/64/7f5d45a782be53b88e5d0963b1ef9a9fc3c6ff409fbbd2006418c5b285ff/tex-1.8.tar.gz
  md5: ac0e996e8154cd7e64ab84d2cc74d1cf

build:
  noarch: python
  number: 1

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - tex

about:
  home: http://www.profv.de/python-tex/
  license: MIT License
  summary: 'Convert LaTeX or TeX source to PDF or DVI, and escape strings for LaTeX.'
  license_family: MIT
