package:
  name: mne
  version: "0.13.1"

source:
  fn: mne-0.13.1.tar.gz
  url: https://pypi.python.org/packages/2f/1f/f7db5c21d8815da1448bf947849b8b501e26d1a03716b27e60073c5fc187/mne-0.13.1.tar.gz
  md5: 51cc1e955e96e7fa8c3f900895fc471a

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - matplotlib
    - pysurfer
    - scikit-learn
    - scipy

test:
  # Python imports
  imports:
    - mne
    - mne.beamformer
    - mne.beamformer.tests
    - mne.channels
    - mne.channels.tests
    - mne.commands
    - mne.commands.tests
    - mne.connectivity
    - mne.connectivity.tests
    - mne.data
    - mne.datasets
    - mne.datasets._fake
    - mne.datasets.brainstorm
    - mne.datasets.eegbci
    - mne.datasets.megsim
    - mne.datasets.misc
    - mne.datasets.multimodal
    - mne.datasets.sample
    - mne.datasets.somato
    - mne.datasets.spm_face
    - mne.datasets.testing
    - mne.datasets.tests
    - mne.decoding
    - mne.decoding.tests
    - mne.externals
    - mne.externals.h5io
    - mne.externals.tempita
    - mne.forward
    - mne.forward.tests
    - mne.gui
    - mne.gui.tests
    - mne.inverse_sparse
    - mne.inverse_sparse.tests
    - mne.io
    - mne.io.array
    - mne.io.array.tests
    - mne.io.brainvision
    - mne.io.brainvision.tests
    - mne.io.bti
    - mne.io.bti.tests
    - mne.io.cnt
    - mne.io.cnt.tests
    - mne.io.ctf
    - mne.io.ctf.tests
    - mne.io.edf
    - mne.io.edf.tests
    - mne.io.eeglab
    - mne.io.egi
    - mne.io.egi.tests
    - mne.io.fiff
    - mne.io.fiff.tests
    - mne.io.kit
    - mne.io.kit.tests
    - mne.io.nicolet
    - mne.io.nicolet.tests
    - mne.io.tests
    - mne.minimum_norm
    - mne.minimum_norm.tests
    - mne.preprocessing
    - mne.preprocessing.tests
    - mne.realtime
    - mne.realtime.tests
    - mne.simulation
    - mne.simulation.tests
    - mne.stats
    - mne.stats.tests
    - mne.tests
    - mne.time_frequency
    - mne.time_frequency.tests
    - mne.viz
    - mne.viz.tests

about:
  home: http://martinos.org/mne
  license: BSD (3-clause)
  summary: 'MNE python project for MEG and EEG data analysis.'
  license_family: BSD
