os: osx
language: r
sudo: false
# https://github.com/travis-ci/travis-ci/issues/2312

cache:  # https://docs.travis-ci.com/user/caching/
  - packages
  - pip

#python:
#  - 2.7

r_packages:
  - car
  - ez

# Setup anaconda
# https://gist.github.com/dan-blanchard/7045057
before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes --quiet conda
  - conda config --append channels conda-forge
  - conda config --append channels christianbrodbeck
  - conda install --yes --quiet --file requirements.txt
  - conda install --yes --quiet nose
  - pip install rpy2
  - python -c "import mne; mne.datasets.testing.data_path()"
  - python --version

install:
  - python setup.py develop

script:
  - make test
