{% set version = "0.31a2" %}
{% set sha256 = "d7e77bce8eb7eb492a2beb85ca63bb8222ee48dcd0675fdd94f5571fa8f2f5a2" %}

# https://github.com/conda/conda-build/issues/2717

package:
  name: eelbrain
  version: {{ version }}

source:
  fn: eelbrain-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/eelbrain/eelbrain-{{ version }}.tar.gz
  sha256: {{ sha256 }}
#  path: ../../

build:
  number: 0
  osx_is_app: True

requirements:
  build:
    - python  {{ python }}
    - python.app  # [osx]
    - cython >=0.21
    - olefile  # [win or linux]
    - pywin32-ctypes  # [win]
    - setuptools >=17
    - numpy 1.11.*
    - libblas
    - libcblas

  run:
    - python  {{ python }}
    - python.app  # [osx]
    - colormath >=2.1
    - ipython
    - keyring >=5
    - matplotlib >=3
    - mne >=0.17
    - nibabel >=2.0, !=2.3.0
    - olefile  # [linux]
    - {{ pin_compatible('numpy') }}
    - pillow
    - pysurfer >=0.8
    - nilearn
    - scipy >=1.3
    - tqdm >=4.8
    - wxpython >=4.0.3
    - mayavi >=4.6.2

test:
  # Python imports
  imports:
    - eelbrain
    - eelbrain.load
    - eelbrain.mne_fixes
    - eelbrain.plot
    - eelbrain.save

about:
  home: http://eelbrain.readthedocs.io
  summary: 'MEG/EEG analysis tools'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: http://eelbrain.readthedocs.io/
  dev_url: https://github.com/christianbrodbeck/eelbrain

# See for more information about meta.yaml:
# https://veranostech.github.io/docs-korean-conda-docs/docs/build/html/user-guide/tasks/build-packages/define-metadata.html
