package:
  name: eelbrain
  version: "VERSION"

source:
  path: ../../

build:
  number: 0
  osx_is_app: True

requirements:
  build:
    - python
    - python.app  # [osx]
    - cython >=0.21
    - olefile  # [win or linux]
    - pywin32-ctypes  # [win]
    - setuptools >=17
    - numpy x.x

  run:
    - python
    - python.app  # [osx]
    - colormath >=2.1
    - ipython
    - keyring >=5
    - matplotlib >=1.1
    - mne >=0.14
    - nibabel >=2.0
    - olefile  # [linux]
    - numpy x.x
    - pillow
    - pysurfer >=0.7
    - scipy >=0.17
    - tex >=1.8
    - tqdm >=4.8
    - wxpython

test:
  # Python imports
  imports:
    - eelbrain
    - eelbrain.load
    - eelbrain.mne_fixes
    - eelbrain.plot
    - eelbrain.save

about:
  home: https://pythonhosted.org/eelbrain
  summary: 'MEG/EEG analysis tools'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
