{% set version = "0.28rc1" %}
{% set sha256 = "5a71e31da66426db23dadd8fca3b77d476431c1c60a8db6a6608f9984226ca90" %}

# https://github.com/conda/conda-build/issues/2717

package:
  name: eelbrain
  version: {{ version }}

source:
  fn: eelbrain-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/eelbrain/eelbrain-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  osx_is_app: True

requirements:
  build:
    - python  {{ python }}
    - python.app  # [osx]
    - cython >=0.21
    - olefile  # [win or linux]
    - pywin32-ctypes  # [win]
    - setuptools >=17
    - numpy 1.11.*

  run:
    - python  {{ python }}
    - python.app  # [osx]
    - colormath >=2.1
    - ipython
    - keyring >=5
    - matplotlib >=2.1
    - mne >=0.15.2
    - nibabel >=2.0
    - olefile  # [linux]
    - {{ pin_compatible('numpy') }}
    - pillow
    - pysurfer >=0.8
    - scipy >=0.17
    - tqdm >=4.8
    - wxpython >=4

test:
  # Python imports
  imports:
    - eelbrain
    - eelbrain.load
    - eelbrain.mne_fixes
    - eelbrain.plot
    - eelbrain.save

about:
  home: https://pythonhosted.org/eelbrain
  summary: 'MEG/EEG analysis tools'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
