{% set version = "0.26.5" %}
{% set md5 = "83d66fec404e6197e12314105a6949b2" %}

package:
  name: eelbrain
  version: {{ version }}

source:
  fn: eelbrain-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/eelbrain/eelbrain-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0
  osx_is_app: True

requirements:
  build:
    - python  {{ python }}
    - python.app  # [osx]
    - cython >=0.21
    - olefile  # [win or linux]
    - pywin32-ctypes  # [win]
    - setuptools >=17
    - numpy  {{ numpy }}

  run:
    - python  {{ python }}
    - python.app  # [osx]
    - colormath >=2.1
    - ipython
    - keyring >=5
    - matplotlib >=1.1
    - mne >=0.14
    - nibabel >=2.0
    - olefile  # [linux]
    - numpy
    - pillow
    - pysurfer >=0.8
    - scipy >=0.17
    - tex >=1.8
    - tqdm >=4.8
    - wxpython

test:
  # Python imports
  imports:
    - eelbrain
    - eelbrain.load
    - eelbrain.mne_fixes
    - eelbrain.plot
    - eelbrain.save

about:
  home: https://pythonhosted.org/eelbrain
  summary: 'MEG/EEG analysis tools'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
