name: Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    - name: Install Mamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: env-dev.yml
        environment-name: eeldev
        init-shell: bash
        cache-environment: true
        post-cleanup: 'all'
    - name: build Eelbrain
      run: pip install -e .
      shell: bash -el {0}
    - name: Test with pytest
      env:
        DISPLAY: :99
      run: |
        Xvfb :99 -screen 0 1024x768x16 &
        export DISPLAY=:99
        pytest --cov --cov-report=xml
      shell: bash -el {0}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
